#!/bin/bash

function nl() {
echo ""
}



RED='\033[0;31m'
YELLOW='\033[0;33m'
CYAN='\033[0;34m'
NC='\033[0m'


nl
nl
echo -e "${RED}invalid command${NC} \"${YELLOW}prosec${NC}\". Displaying help menu"
nl
nl
echo -e "${CYAN}prosec-install${NC}: adds a module to the modlue directory"
nl
echo -e "${CYAN}prosec-run${NC}: runs modules in the module directory"
nl
echo -e "${CYAN}prosec-list${NC}: lists avalible modules in the directory"
nl
nl
echo -e "${YELLOW}\"note* if you wish to get any info use -h on any command for more indepth info\" ${NC}"
nl
nl